# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: uv sync --frozen
    name: uv sync --frozen
    entry: uv sync --frozen
    language: system
    pass_filenames: false
    require_serial: true
    always_run: true

  - id: uvx ruff format --check
    name: uvx ruff format --check
    entry: uvx ruff format --check
    language: system
    pass_filenames: false
    always_run: true

  - id: uvx ruff check
    name: uvx ruff check
    entry: uvx ruff check
    language: system
    pass_filenames: false
    always_run: true
    